server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateaway:
      routes:
        - id: USER-SERVICE
          uri: http://localhost:9002
          predicates:
            - Path=/users/**
        - id: DEPARTMENT-SERVICE
          uri: http://localhost:9001
          predicates:
            - Path=/departments/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
